# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.4"

[source]
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = []

[format]
print_width = 120
tab_width = 4
use_tabs = false
inline_empty_anonymous_class_braces = true
inline_empty_classlike_braces = true
inline_empty_closure_braces = true
inline_empty_constructor_braces = true
inline_empty_control_braces = true
inline_empty_function_braces = true
inline_empty_method_braces = true
null_type_hint = "Question"

[linter]
default_plugins = true
plugins = ["symfony", "php-unit"]

[[linter.rules]]
name = "best-practices/literal-named-argument"
level = "off"

[[linter.rules]]
name = "php-unit/assertions-style"
style = "this"

[[linter.rules]]
name = "naming/interface"
psr = false

[[linter.rules]]
name = "naming/trait"
psr = false

[[linter.rules]]
name = "naming/class"
psr = false
